app:
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey
server:
  port: 8006
spring:
  ldap:
    embedded:
      base-dn: dc=jforce,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:schema.ldif
      port: 12345
      validation:
        enabled: false
        
eureka: 
  client: 
    serviceUrl:
      defaultZone:  http://192.168.23.134:8761/eureka/  
    register-with-eureka: true
    fetch-registry: true
    
jwt:
  header: Authorization
  secret: mySecret
  expiration: 50000
  route:
    authentication:
      path: /user/signin
      signup: /user/signup
ribbon:
  ReadTimeout : 60000
          
security:
   basic:
      enable : false   
zuul:
  routes:
    kyc-information: 
        path: /boa-kyc-information-service/**
        service-id: boa-kyc-information-service   
    apply-loan: 
        path: /boa-apply-loan-service/**
        service-id: boa-apply-loan-service
    income-information: 
        path: /boa-income-information-service/**
        service-id: boa-income-information-service          
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        